version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    hostname: app
    tty: true
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    stdin_open: true