version: '3.7'
services:
  app:
    build: docker
    container_name: app
    hostname: app
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/client
    networks:
      fincorp-network:
        aliases:
          - app
    ports:
      - "3000:3000"
    stdin_open: true
volumes:
  .:
networks:
  fincorp-network: